agents:

  GSAgent:
    model_platform: "deepseek"
    model_type: "deepseek-chat"
    api_key: "sk-5d5bcc8fe6cc46a69645ec4e2a705ca4"
    url: "https://api.deepseek.com"
    model_config_dict:  # Additional model configuration
      temperature: 0.7
# Research Projects Configuration
projects:
  project_manager:
    config_path: projects.yml