agents:

  GSAgent:
    model_platform: "deepseek"
    model_type: "deepseek-chat"
    api_key: "xxxx"
    url: "https://api.deepseek.com"
    model_config_dict:  # Additional model configuration
      temperature: 0.7
# Research Projects Configuration
projects:
  project_manager:
    config_path: projects.yml